name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag morkot/mtr:latest
    
    - name: Login to Dockerhub
      env:
        DOCKER_HUB_TOKEN: ${{ secrets. DOCKER_HUB_TOKEN}}
      run: echo ${DOCKER_HUB_TOKEN} | docker login --username morkot --password-stdin
    
    - name: Push the Docker image to Dockerhub
      run: docker push morkot/mtr:latest
