name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag morkot/mtr:latest
    
    - name: Logon to Dockerhub
      env:
        DOCKER_HUB_TOKEN: ${{ secrets. DOCKER_HUB_TOKEN}}
      run: docker login --username morkot --password ${DOCKER_HUB_TOKEN}
    
    - name: Push the Docker image
      run: docker push morkot/mtr:latest
    
    - name: Clean docker creds and stuff
      run: rm -rf /home/runner/.docker/
